### ISSUE TITLE
Incorrect Assembly of certain numbers

### ISSUE THREAD

**Issue by Electronics** [hlorenzi/customasm#1]
```
#align 24
JNZ {check_addr}, {branch_addr} -> 6'0x04 @ check_addr[4:0] @ 5'0 @ branch_addr[7:0]
```
will produce `f*****` whatever the input when it should be `1*****`. By changing the above to
```
#align 24
JNZ {check_addr}, {branch_addr} -> 6'0x04 @ 18'0x00
```
it works correctly. Seems to be something to do with the alignment and how it concatenates bits together.

**Comment by hlorenzi** [comment]
Wow, good catch! I've fixed it, it's in the `dev` branch.

Did you download from Releases or compile it yourself? Just please be warned that I've been changing some syntax in the `dev` branch; docs are still incomplete.

Let me know if you need anything! I'd love to know what you're working on.

**Comment by Electronics** [comment]
That was from the releases, I'm working on an assignment at the moment to produce a FPGA-synthesisable picoMIPS processor capable of the affline transformation. I've got it all working now and this assembler has been so useful in programming the thing!

**Comment by hlorenzi** [comment]
I've added a new release which includes this fix!

If you try it out, could you please let me know if the new way to define a CPU helps? I'm afraid it might be more cumbersome in some cases...

And that is an awesome project you're working on! If possible, keep me updated. We should chat! 😜
