### ISSUE TITLE
Add C source file output format

### ISSUE THREAD

**Issue by quicktom** [hlorenzi/customasm#10]
Hi, this is the tool I was looking for. Thanks. Great for custom FPGA processors.

Could you please make a --format "c" which creates a c source file 
which contains an array with the binary?

This would be make it more easy to integrate the binary into xilinx sdk or altera.

Regards
Thomas

**Comment by hlorenzi** [comment]
I've added a C source format (use format codes `c`, `decc`, or `hexc`)! I'd love to hear what you think!
