### ISSUE TITLE
Please allow ":" and "=" characters in target ISA syntax

### ISSUE THREAD

**Issue by jerry-D** [hlorenzi/customasm#109]
Hi,

I just published a Rule table for the new 64-bit, SYMPL Universal Floating-Point ISA at the SYMPL Compute Engines page at GitHub:  https://github.com/jerry-D

Originally, I had been using "Cross-32" table-driven cross-assembler, which permits ":" and "=" characters in the target ISA syntax.  Please refer to the SYMPL CustomASM repository for a description of the problem and example code:

https://github.com/jerry-D/CustomASM-for-SYMPL-ISA

The new 64-bit ISA is the first to dispense with "op-codes" altogether.  It is strictly typed, having DEST, srcA, and srcB fields, each having their own 4-bit "size" fields.  The ":" character is used in the ISA syntax to separate the "size" fields from the respective Dest, srcA and srcB fields.  Since there are no "op-codes", the ISA native language looks more like a higher-level intermediate representation, wherein the "=" character is used immediately to the right of the destination and immediately to the left of any source operands.  Thus, the new ISA is a pure "mover" architecture, wherein it can push dual operands of up to 128 bytes (1024 bits) each into a given memory-mapped operator every clock cycle, especially when preceded by the REPEAT operator.  I won't go into details here, but you can find out more about the new ISA in this .pdf document:  

https://github.com/jerry-D/SYMPL_IEEE754-2019_ISA/blob/main/UFP_ISA.pdf 

Thus, this is a request that CustomASM be updated to support ":" and "=" in the target ISA syntax.

Thank you.

Jerry

**Comment by moonheart08** [comment]
So, unfortunately, this is _super_ non-trivial. The reason it's not currently supported is that the assembler *already assigns a meaning to = and :*. Supporting them would make parsing even more of a nightmare than it already is.

**Comment by jerry-D** [comment]
moonheart08, I doubt very seriously your assertion that it can't be done, and, consequently, I doubt very seriously you know what you are talking about.  In this instance, the ISA uses "=" and ":"  outside any expression, ie, braces.  

":" is only used by the assembler to distinguish a label from a constant, and "=" is used to distinguish a constant from a label.  Simply adopt the rule that all labels and constant names begin in the first column.  If a name begins in first column and is terminated with ":", it's a label; if followed by a "=", it's a constant.  After that, a ":" and a "=" occurring outside braces "{....}" are treated like any other character,

**Comment by moonheart08** [comment]
@jerry-D The fact it already has uses for other expressions is what makes it nontrivial. The implementation of `(` `)` in patterns is equally non-trivial. The issue is avoiding syntax overlap with constants and labels, which would make the whole language whitespace sensitive by necessity, from what I know of the parser.

And please don't go around telling people they don't know what they're talking about. They are far less inclined to help you if you proclaim they don't know how things work. If that's the attitude you wish to have, you should implement this yourself, as clearly you do know what you are talking about and should know how to implement it.

**Comment by jerry-D** [comment]
This is to report that there is an exceedingly trivial solution to allowing "=" and ":" characters in the target ISA syntax (at least as pertains to the SYMPL ISA syntax.)  Simply go to source/syntax/token.rs file and modify the "is_allowed_pattern_token" function by including the following lines among the others:

		self == TokenKind::Equal ||          //added by J.D.H. 8/31/2021
		self == TokenKind::Colon ||          //added by J.D.H. 8/31/2021

The SYMPL CustomASM repository has been updated to include the demo source assembly code with ":" and "=" in the target ISA syntax.  Once you modify the above file, run "cargo build" command to create new customASM executable, which will be located in the your rust target/debug/ folder.

**Comment by moonheart08** [comment]
> 
> 
> This is to report that there is an exceedingly trivial solution to allowing "=" and ":" characters in the target ISA syntax (at least as pertains to the SYMPL ISA syntax.) Simply go to source/syntax/token.rs file and modify the "is_allowed_pattern_token" function by including the following lines among the others:
> 
> ```
> 	self == TokenKind::Equal ||          //added by J.D.H. 8/31/2021
> 	self == TokenKind::Colon ||          //added by J.D.H. 8/31/2021
> ```
> 
> The SYMPL CustomASM repository has been updated to include the demo source assembly code with ":" and "=" in the target ISA syntax. Once you modify the above file, run "cargo build" command to create new customASM executable, which will be located in the your rust target/debug/ folder.
> 
> Hopefully, the original author of CustomASM will see fit to make these changes to the official version and publish an executable at its repository.

I don't think you are using your head. This isn't at all the reason adding them is hard. It's all the things you proceed to break without fixing, like the standard usages of : and =, which can now conflict with the user defined grammar. It's not a proper fix unless every edge case is accounted for.

```
#ruledef
{
    foo = {value} => value`4 @ 0x0
	test: {value} => value`4 @ 0x1
}

lab:
	foo = 0
	bar = 1
	baz = foo
	foo = bar
test: 3
	foo = 3 + 3
```

**Comment by jerry-D** [comment]
Sorry, moonheart, but your example is absurd and meaningless.  First of all, I see no mnemonics in your example.  CustomASM comprehends that a program to be assembled by it employs mnemonics, and such mnemonic will appear on a line before anything else except for maybe a label.  

SYMPL ISA, like all assembly languages I know of, employ mnemonics.  Your absurd example does not.  Consequently, your example is not "assembly" language and therefore, CustomASM will never be able to assemble it.

SYMPL ISA presently employs only 7 mnemonics:  "_", "P", "N", "Z", "ACT", "ACC",  and "AA".  These mnemonics do not represent opcodes, but rather "modes".  For example, "_" means default rounding mode.  P, N, and Z mean round toward positive, round toward negative or toward zero, respectively.  ACT, ACC and AA are for use with fused artificial neural networks.  Respectively, they mean activate, accumulate, and activate & accumulate.  

I'm sorry you are upset that my solution actually works, at least for the SYMPL ISA syntax.   Please, let's do move on.

**Comment by moonheart08** [comment]
> 
> 
> Sorry, moonheart, but your example is absurd and meaningless. First of all, I see no mnemonics in your example. CustomASM comprehends that a program to be assembled by it employs mnemonics, and such mnemonic will appear on a line before anything else except for maybe a label.
> 
> SYMPL ISA, like all assembly languages I know of, employ mnemonics. Your absurd example does not. Consequently, your example is not "assembly" language and therefore, CustomASM will never be able to assemble it.
> 
> SYMPL ISA presently employs only 7 mnemonics: "_", "P", "N", "Z", "ACT", "ACC", and "AA". These mnemonics do not represent opcodes, but rather "modes". For example, "_" means default rounding mode. P, N, and Z mean round toward positive, round toward negative or toward zero, respectively. ACT, ACC and AA are for use with fused artificial neural networks. Respectively, they mean activate, accumulate, and activate & accumulate.
> 
> I'm sorry you are upset that my solution actually works, at least for the SYMPL ISA syntax. Please, let's do move on.

you just missed the point entirely.

**Comment by moonheart08** [comment]
You are free to make a fork of this program and modify it to suite your needs, but as is your patch is not workable due to lacking error handling and not handling edge cases.

**Comment by jerry-D** [comment]
For the SYMPL ISA syntax, the patch works just fine in every respect, moonheart08.

**Comment by hlorenzi** [comment]
I usually struggle with trying to sound polite online, given that English isn't my native language, so I'm generally willing to give people the benefit of the doubt in this regard. But I see now you're just being extremely rude and condescending towards another contributor to the project, who, by the way, is raising very good points on why your initial suggestion isn't completely desirable.

I know full well the two-line modification necessary to make your suggestion work, but as moonheart08 graciously demonstrated, we need to account for edge cases and error reporting, to make this syntax conflict as obvious to the user as possible -- which was, in fact, the reason for why this was disallowed in the first place.

Now, we could actually be productively discussing how to integrate this idea into the official project -- my suggestion being a special command-line argument which would enable the extra tokens at the user's own risk -- but I think right now the most productive course of action is giving you time to cool off and rethink your manners, @jerry-D.

**Comment by jerry-D** [comment]
Thank you for finally taking the time to respond and for creating such a great product, hlorenzi.  I have to admit that use of ":" and "=" in the SYMPL ISA syntax is way more aesthetically pleasing to the eye than "|" and "<-".   In this respect, I cannot describe how happy and pleased I am with CustomASM and have high hopes for it in the future.  J
