### ISSUE TITLE
Web version doesn't work on edge

### ISSUE THREAD

**Issue by voldemoriarty** [hlorenzi/customasm#11]
Clicking the assemble button has no effect on MS Edge. The console reports an error "TextEncoder" is not defined.

**Comment by bjorn3** [comment]
As far as I know, ms edge doesnt yet support wasm. Because the web version uses wasm to run the rust code in the browser, it doesnt work in edge.

**Comment by hlorenzi** [comment]
It was actually an issue with `TextEncoder` and `TextDecoder`! I've added polyfills for both, and the web version should now work in Edge!
