### ISSUE TITLE
VSCode Syntax highlighting not working.

### ISSUE THREAD

**Issue by jso8910** [hlorenzi/customasm#129]
I have installed CustomASM (the command works) and opened up VSCode to install the extension. I installed it but, however, when I create a file (eg `main.asm`) and type `#ruledef` or copy an example, the syntax is not highlighted. What is my issue?

**Comment by jso8910** [comment]
Fixed! I needed to click at the bottom where it said "ASM" and switch it to "customasm"

**Comment by hlorenzi** [comment]
That's right! You need to switch languages manually since I think VSCode can't decide from the .asm extension or syntax alone.
