### ISSUE TITLE
Add option for addressing units when outputting intelhex?

### ISSUE THREAD

**Issue by fisherdog1** [hlorenzi/customasm#132]
Outputted intel hex files are indexed in bytes, which isn't affected by the bits directive it seems.

https://github.com/hlorenzi/customasm/blob/71bacc12021feefa4d598d9cc57d2d07ad893861/src/util/bitvec_format.rs#L223

This causes an issue if the hex file is then used as memory initialization in Quartus IP or its memory content editor, if the targeted memory expects something other than a byte address; in this example it expects a 16 bit word address:

```
:200000007FFF7E7F7D107C00C0EA2DD0C0FA7001C00CC00CF000C004C1040201C01CC00CCE
:04002000C02CF9F9FE
:00000001FF
```

![image](https://user-images.githubusercontent.com/8609218/161292936-0a5dbd91-3c26-4132-b9fa-b8181a8938f7.png)

Suggest an option like `--addressunit` but probably not a directive as I'm unsure if this is an issue with any other formats.

**Comment by hlorenzi** [comment]
We should be able to implement this with the new "format argument" syntax in v0.13.0!
