### ISSUE TITLE
Relative Jumps?

### ISSUE THREAD

**Issue by KnedlikMCPE** [hlorenzi/customasm#143]
Hello, I'm using this for a virtual ISA under the name ETCa, which mainly uses relative jumps. So I'm quickly asking - is there a way to get the current line's beginning address or any other way to make relative jumps work?
Thanks in advance,
-Knedlik

**Comment by hlorenzi** [comment]
Yes! The `$` variable always contains the address of the current instruction. You can see [on the 6502 CPU definition](https://github.com/hlorenzi/customasm/blob/main/examples/nes/cpu6502.asm#L5) how it's used with relative jumps.

**Comment by KnedlikMCPE** [comment]
Thanks, that does the job!

**Comment by partisani** [comment]
uhh, the link you provided seems to be broken

**Comment by hlorenzi** [comment]
I've fixed it now. Thanks!
