### ISSUE TITLE
v0.11 syntax error using a'b instead of b`a syntax for a constant with a specified width

### ISSUE THREAD

**Issue by sparr** [hlorenzi/customasm#158]
With v0.10 the literal `a'b` represented the constant `b` output with a width of `a` bits, equivalent to ``b`a``. In 0.11.7, this syntax produces an error 'invalid digits'.

The lowest level code for calculating widths and parsing `'` characters hasn't changed. `'` is still a valid character in `is_number_mid` and still recognized as the separator in `parse_width`. I wasn't able to track down the change in behavior.

Test case:

v0.10
```customasm
#cpudef
{
    x -> 8'5
}

x
```
outputs `0x05`

v0.11.7
```customasm
#ruledef
{
    x => 8'5
}

x
```
error `invalid digits` for the `8'5` excerpt

**Comment by hlorenzi** [comment]
I think it was my intention to deprecate the old syntax, so I've now completely removed the residual code!

**Comment by sparr** [comment]
Could we get a mention in the docs, perhaps in a section dedicated to
deprecated functionality, so that people will know how to update old code?
This was nontrivial for me because I didn't know what the syntax I was
seeing was supposed to do. I had to read the source and/or browse old
versions.
