### ISSUE TITLE
Cannot reference variables in #bankdef

### ISSUE THREAD

**Issue by vxgmichel** [hlorenzi/customasm#168]
This is a regression starting with `v0.13.0`.

The following code used to work:
```asm
HEADER_SIZE = 0x34
#bankdef header {#addr 0, #size HEADER_SIZE, #outp 0}
```

Now it produces:
```asm
error: cannot reference variables in this context
 --> asm:2:33:
1 | HEADER_SIZE = 0x34 
2 | #bankdef header {#addr 0, #size HEADER_SIZE, #outp 0} 
  |                                 ^^^^^^^^^^^            
3 | 
```

Using variables in `#bankdef` is pretty convenient, any hope to see this fixed in a future release? :)

**Comment by hlorenzi** [comment]
Yeah, sorry! That's supposed to work.
I'm working on it!

**Comment by hlorenzi** [comment]
Should work now on v0.13.1!
