### ISSUE TITLE
!128 calculated incorrectly

### ISSUE THREAD

**Issue by rj45** [hlorenzi/customasm#17]
For some reason, !128 is "00000000 01111111" when it should be "11111111 01111111".

Interestingly, !256 is "11111110 11111111" and !64 is  "11111111 10111111".

I did manage to fix it by making bigint_not look like this:

```rust
fn bigint_not(x: BigInt) -> BigInt
{
	bigint_bitmanipulate(x, BigInt::zero(), |a, _b| !a)
}
```

But my rust skills are pretty much nil and I am sure there is a more elegant solution, otherwise I would cook up a PR for you.

**Comment by hlorenzi** [comment]
Thank you for reporting the bug! I've had to fix it in a different way, to avoid breaking other test cases: (additions marked with +)

```rust
fn bigint_not(x: BigInt) -> BigInt
{
	let mut x_bytes = x.to_signed_bytes_le();
	
+	if x.sign() != Sign::Minus
+		{ x_bytes.push(0); }
	
	for i in 0..x_bytes.len()
		{ x_bytes[i] = !x_bytes[i]; }
	
	BigInt::from_signed_bytes_le(&x_bytes)
}
```

Anyway, this was just a quick fix. I've got to investigate these BigInt issues further, as I think the library has been updated with more bit manipulation support, but I don't have time to do it right now.

**Comment by rj45** [comment]
Thanks for the quick fix!
