### ISSUE TITLE
feature request: api for own rust programs

### ISSUE THREAD

**Issue by NikOverflow** [hlorenzi/customasm#175]
My idea is that you make an api that can be used in rust programs.

**Comment by hlorenzi** [comment]
You should be able to include `customasm` as a `cargo` dependency already. The [lib.rs file](https://github.com/hlorenzi/customasm/blob/main/src/lib.rs) exposes the internal modules that you can use in your own code, as is demonstrated by the `assemble_str_to_binary` function contained in the same file. Are you facing any particular issues?
