### ISSUE TITLE
Allow Constants as Slice Sizes

### ISSUE THREAD

**Issue by eignnx** [hlorenzi/customasm#189]
As a new user of `customasm`, I expected this to be possible:

```
#const MWordSz = 12
#const RegI = (1 << 0)`MWordSz
```

But I get this error:

```
customasm v0.13.4 (2023-11-04, x86_64-pc-windows-msvc)
assembling `microlark.customasm`...
error: expected number
 --> microlark.customasm:7:24:
7 | #const RegI = (1 << 0)` MWordSz
  |                        ^
```

Is there a better way to do this? Or could this feature be added?

**Comment by hlorenzi** [comment]
For some reason, I made the slice size operand require a number literal, probably to facilitate some feature in an old architecture of the program, but I think it should be easy to lift this restriction now.
