### ISSUE TITLE
Custom register names -- Feature request

### ISSUE THREAD

**Issue by milanvidakovic** [hlorenzi/customasm#2]
Hello,
I am developing a custom cpu with the following syntax:
mov r0, r1  -> 4'0x1 @ 4'0x0 @ 4'0x0 @ 4'0x1
mov r3, r2  -> 4'0x2 @ 4'0x3 @ 4'0x0 @ 4'0x1

Is it possible to make a rule like this:
mov r{d}, r{s}  -> s[3:0] @ d[3:0] @ 4'0x0 @ 4'0x1

I have eight registers and this would make my syntax file significantly shorter.
Best regards,
Milan

**Comment by hlorenzi** [comment]
Yes! This is high on the list.

I've got [another request for something like this, but for uniquely-named registers](https://gist.github.com/Nullious/b71a9b14719ffaaa52d39ff440c618b0) -- I might want to offer a solution to both soon. Though it may be a while until I can work on this.

As a workaround for now, you could use register names with a space between the `r` and the number: `mov r 1, r 2` I believe this won't clash with other rules.

**Comment by milanvidakovic** [comment]
Hi,
Thanks for the response! I am looking forward to this feature in your project.

As you know, I have forked your project and added two features: 
1. output format for the LogiSim digital components simulator (-f hexstr2), and
2. #str16 string format (16-bit characters, like UTF16)

Feel free to include them in your project if you find them useful.
Best regards,
Milan

**Comment by milanvidakovic** [comment]
Hello,
Thanks for the release with the tokendef. I have already modified my big instruction set to the reduced one, but I have encountered this problem:

ld {dest: reg}, [{src: reg} + {value}] -> src[3:0]  @ dest[3:0] @ 4'0x2 @ 4'0x2 @ value[15:0]

The line above causes the error message:
error: ambiguous pattern token after parameter
ld {dest: reg}, [{src: reg} + {value}] -> src[3:0]  @ dest[3:0] @ 4'0x2 @ 4'0x2 @ value[15:0]
                                      ^
The idea is that I could make this:
ld r0, [r1 + 5]

Am I doing something wrong, or this could be another feature request?

Best regards,
Milan

**Comment by hlorenzi** [comment]
The idea of that error message was to avoid situations like
```
ld {src} + {dest} -> ...
```
with integer parameters, since then it's not possible to disambiguate an usage like `ld 1 + 2 + 3`.

But as tokendef parameters are fixed, this can actually be considered an oversight, and I can just relax the error checking a little to allow it.

**Comment by milanvidakovic** [comment]
Hi,
Thanks for the quick response. Yes, that would be great if you could relax the error checking to allow that kind of operation between arguments. Especially when the phrase includes something like: 
{src: reg} + {value}. That  ": reg" could help in determining that one of the operands for the "+" is actually the register.

Best regards,
Milan
