### ISSUE TITLE
[Feature Request]: Have a `=` in the mnemonics.

### ISSUE THREAD

**Issue by SohamTilekar** [hlorenzi/customasm#207]
- This Should Be implemented Because it add the Ability to make the new ASM Syntax more Beautifull.
E.G: -
```asm
    ADD R0 = R1, R2
```
- This Will Be not that hard to Implement😜.

**Comment by SohamTilekar** [comment]
This Can Be Done Easily by Just checking that the next character is not the >, I don't Know How to Use the RUST otherwise I have implemented it.

**Comment by hlorenzi** [comment]
The equals sign is explicitly disallowed in mnemonics because it has another syntax function, in the declaration of constants. At this point, I'm inclined to leave this rule in place.
