### ISSUE TITLE
Usage as a library

### ISSUE THREAD

**Issue by ClementNerma** [hlorenzi/customasm#21]
Hi,

I'm currently developping a virtual machine library that uses custom instructions, which means a custom assembly language.

I've used CustomASM for a while now using the CLI and I really enjoy the possibility of the projects (alignment, labels, arithmetic, etc.), but I'd like to integrate it to my library. Sadly, when I looked at your files, it doesn't seem you expose enough functions to enable concrete usage as a library :/

Do you have any plan to enable such usage? It'd be really great to be able to do something like:

```rust
let src: &'static str = "<<< asm code here >>>";
let hex: Vec<u8> = customasm::assemble_to_hex(src).unwrap();

println!("Hex: {}", hex);
```

Thanks in advance for your answer :)

**Comment by hlorenzi** [comment]
There could absolutely have a more convenient function for this use-case, but as of now, if you take a look at [the webasm interface](https://github.com/hlorenzi/customasm/blob/master/src/webasm/mod.rs#L9), it shows a way you can do it. Then, you may use `output.generate_binary(0, output.len())` to generate a byte vector. Let me know if you need more help!

**Comment by ClementNerma** [comment]
I indeed saw this method, but sadly it's unsafe and I'm working in a crate that forbids any `unsafe` block :/
Is there any other way to use the library without unsafe?

**Comment by hlorenzi** [comment]
You can remove the unsafe parts; maybe something like the following? I haven't tested it, though:

```rust
fn assemble(src: &str) -> Vec<u8>
{
	let mut fileserver = FileServerMock::new();
	fileserver.add("asm", src.clone());
	
	let assemble = |report: RcReport, fileserver: &FileServerMock, filename: &str| -> Result<Vec<u8>, ()>
	{
		let mut asm = AssemblerState::new();
		asm.process_file(report.clone(), fileserver, filename)?;
		asm.wrapup(report.clone())?;
		
		let output = asm.get_binary_output();
		Ok(output.generate_binary(0, output.len()))
	};
		
	let report = RcReport::new();
	
	match assemble(report.clone(), &fileserver, "asm")
	{
		Ok(output) => output,
		Err(_) => panic!("error assembling")
	}
}
```

**Comment by hlorenzi** [comment]
I've added a new function, so you can now do:
```rust
customasm::assemble_str_to_binary("your string")
```

You can retrieve the byte array by doing:
```rust
let bytes = customasm::assemble_str_to_binary("your string").0.unwrap();
```

**Comment by ClementNerma** [comment]
Sorry for the late answer I just received for notification.
Thanks a lot for the new function, it's really more simple to use now 👍
