### ISSUE TITLE
[v0.10.4] "thread 'main' panicked at 'at partial', src\syntax\parser.rs:89:6" Error

### ISSUE THREAD

**Issue by ProxyPlayerHD** [hlorenzi/customasm#22]
strangely been getting these Rust Errors instead of regular Assembler erros like "no matching instruction"

no idea if i just got worse at programming that it makes the Assembler crash, or the Assembler got some issue.

here the file i tried to assble and the CPU file:

[CPU FILE](https://pastebin.com/f4xt82n3)

[PROGRAM](https://pastebin.com/mn8U4fsm)

**Comment by hlorenzi** [comment]
It was definitely some issue with the assembler! It should always terminate gracefully with an error report, without panics, no matter the situation.

**Comment by ProxyPlayerHD** [comment]
Still happening with the newest release.. the release on github says 0.10.5 but when you run it in the cmd it says 0.10.4

Did you update the code but not the file you download or am I missing something?

**Comment by hlorenzi** [comment]
Oops, my mistake! It should be fixed now.
Did that small program crash in v0.10.4 too? There should be no trouble in the new version.

**Comment by ProxyPlayerHD** [comment]
That small program crashed 0.10.4 but i just tried it with 0.10.5 and it worked

I also noticed a mistake in my 6502 CPU file. A relative jump should use (src - (pc + 2)) as operant. But my file (and your example 6502?) used (src - (pc - 2))

This is why my programs weren't working.

**Comment by hlorenzi** [comment]
Is that so, about the 6502 branches? I remember looking that up, and because of 6502's internals, most documents seem to treat the current "pc" address differently than what I'm doing in the assembler, hence the discrepancy in the formulas.

I've also checked it, and I'm using `addr - pc - 2` in my CPU file, which is equivalent to the `addr - (pc + 2)` you mentioned, so I think that's correct?

**Comment by ProxyPlayerHD** [comment]
yea i looked it up and the 6502's branches are calculated from the first byte of the next instruction

so using an online assembler:

```
C000        NOP             EA
C001        BNE NEXT        D0 00
C003 NEXT   NOP             EA
C004        NOP             EA
C005        NOP             EA
```
as you can see it jumps to the label "NEXT" which is the iunstruction after the jump. so the relative offset is 0.

**Comment by hlorenzi** [comment]
The `pc` variable in customasm gets the address of the *current* instruction, so in your examples, it would have the value `0xc001`, and not `0xc003`.
