### ISSUE TITLE
Disabling `pc` variable

### ISSUE THREAD

**Issue by ClementNerma** [hlorenzi/customasm#23]
Hi,

I'm currently using CustomAsm for a tiny virtual machine and I recently ran into a problem about the usage of `pc`.

My assembly language has a register named `pc` where the address of the next instruction is stored. This register can be accessed directly, but they do not provide the expected result when used with CustomAsm.

Let's take for instance this code:

```
#cpudef
{
    #bits 8
    
	#tokendef reg {
		pc = 0xAB
	}
	
    ld {reg}, {short} -> 0x01 @ reg[7:0] @ short[15:8] @ short[7:0]
}

#addr 0x100

main:
  ld pc, 0xF0
  ld pc, 0xF0
```

The expected result is:

```
100:0 |  100 | 01 ab 00 f0    ; ld pc, 0xF0
104:0 |  104 | 01 ab 00 f0    ; ld pc, 0xF0
```

But the one CustomAsm provides is:

```
100:0 |  100 | 01 00 00 f0    ; ld pc, 0xF0
104:0 |  104 | 01 04 00 f0    ; ld pc, 0xF0
```

As `pc` is replaced by the address of the current instruction.

So I'd like to know if there is by change any way to either disable or rename this variable? I think it is really useful in programs so it would be great if we'd be able to still use it, but under another name (like for instance `$pc` or something).

Thanks in advance for your answer :)

**Comment by hlorenzi** [comment]
The assembler is using `pc` as an address because you've set up your instruction as `ld {reg}, {short}`, which expects two generic expressions. If you set it up as `ld {reg: reg}, {short}`, which makes the first argument take the `reg` tokendef, then you should have no problem!

**Comment by ClementNerma** [comment]
Oh that's true, I wasn't aware of this. 
Thanks a lot 😄
