### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by milanvidakovic** [hlorenzi/customasm#3]
Hi,
I am using this kind of instruction description:
add r0 -> 4'0x0 @ 4'0x1 @ 4'0x2 @ 4'0x3 
add r1 -> 4'0x1 @ 4'0x1 @ 4'0x2 @ 4'0x3 

Until now, it worked perfectly. However, when I added this description:
add r2 -> 4'0x0 @ 4'0x0 @ 4'0x8 @ 4'0x9
It produced: 0077, instead of 0089

When I described the instruction this way:
add r2 -> 4'0x0 @ 4'0x0 @ 8'0x89 
It produced the correct code: 0089

Also, if I use this:
add r2 -> 4'0x2 @ 4'0x1 @ 4'0x8 @ 4'0x9
It produces the correct code: 2189

If I use this:
add r2 -> 4'0x0 @ 4'0x1 @ 4'0x8 @ 4'0x9
It produces the correct code: 0189

Only when I use:
add r2 -> 4'0x0 @ 4'0x0 @ 4'0x8 @ 4'0x9
it produces the wrong code: 0077

I have only three lines in the instruction description:
add r0 -> 4'0x0 @ 4'0x1 @ 4'0x2 @ 4'0x3 
add r1 -> 4'0x1 @ 4'0x1 @ 4'0x2 @ 4'0x3 
add r2 -> 4'0x0 @ 4'0x0 @ 4'0x8 @ 4'0x9

Am I missing something? I have created hundreds of lines the this way and I have accidentally discovered this problem just today.

Best regards,
Milan

**Comment by hlorenzi** [comment]
Yeah, that was a bug! The second bug found with the concatenation operator, oh well... I've fixed it, will upload soon! Thanks for reporting it! 😃

**Comment by milanvidakovic** [comment]
Thanks for the quick response!
Best regards,
Milan
