### ISSUE TITLE
Runtime Error: unreachable executed

### ISSUE THREAD

**Issue by chocabloc** [hlorenzi/customasm#32]
when assembling the below code:
```
#cpudef
{
    #bits 8
	byte {b} -> b[7:0]
    nop -> 0x00
	set {value}, {reg} -> 0x01 @ value[7:0] @ reg[7:0]
	jmp {address} -> 0x02 @ address[15:0]
	add {val} -> 0x03 @ val[7:0]
	dbg -> 0x04
	sub {val} -> 0x05 @ val[7:0]
	smem {pos},{val} -> 0x06 @ pos[15:0] @ val[7:0]
	rmem {pos},{reg} -> 0x07 @ pos[15:0] @ reg[7:0]
	memr {pos},{reg} -> 0x08 @ pos[15:0] @ reg[7:0]
}

nop

jmp .loop

.string:
	byte 'h'
	byte 'e'
	byte 'l'
	byte 'l'
	byte 'o'
	
.start:
	byte .string
	
.loop:
	rmem .start, 0
	dbg
	set .start, 0
	add 1
	memr .start, 0
```

it shows Runtime Error: unreachable executed

**Comment by hlorenzi** [comment]
Currently, the assembler doesn't accept character literals... I'll be working on this feature.

For now, you may be able to get around this issue by using single-character string literals, like so:

```asm
#str "h"
#str "e"
#str "l"
#str "l"
#str "o"
```

**Comment by hlorenzi** [comment]
I've done this on v0.11! You can use strings in any expression now. You can use something like `byte "h"` in your original program, for example, or something like `#d "hello"` or even `#d "h", "e", "l", "l", "o"`.
