### ISSUE TITLE
Support for character (ASCII) constants

### ISSUE THREAD

**Issue by visrealm** [hlorenzi/customasm#34]
Since adding a character LCD to my project, I often find myself needing to define a character constant. Currently, I need to do something like this:

`ASCII_SPACE = 32`

Would be really nice to be able to do this:

`ASCII_SPACE = ' '`

Optionally, to use a character as an argument in an instruction and have it substiture an ascii value: eg.

`mova ' '`

**Comment by hlorenzi** [comment]
Yes, this would be a very useful feature. I'll try working on it soon!

**Comment by LiQuiD04** [comment]
Agree, #STR is not comfortable.

**Comment by ProxyPlayerHD** [comment]
really hope it gets added, it would be so useful to use ASCII characters as actual values without #str

`LDA ASCII_ZERO`
could be replaced by
`LDA '0'` or `LDA "0"`

**Comment by hlorenzi** [comment]
I've made strings be accepted in any expression in v0.11! You can also use single-character strings, of course (there are no character literals). It should have the same effect as expected in the original post.
