### ISSUE TITLE
thread main panic on bank overlap check

### ISSUE THREAD

**Issue by DerULF1** [hlorenzi/customasm#41]
First of all: Thank you very much for that great assembler!

There is a thread main panic, during bank overlapping check, if the first bank has no outp set:

A simple program to recreate the error looks like this:
#include "6502.cpu"

#bankdef "data"
{ #addr 0x0000, #size 0x2000 }

#bankdef "pgm"
{ #addr 0x2000, #size 0xC000,	#outp 0 }

#bank "pgm"
P: #d8 0

#bank "data"
Q: #res 1

The stack backtrace produced is this:
[stackbacktrace.txt](https://github.com/hlorenzi/customasm/files/4984971/stackbacktrace.txt)

The error disappears if you define the bank without outp after the bank with outp.

I believe the error is in file assembler.rs function check_bank_overlap. The check being done on line 244 for self.bankdefs[j] should be repeated at line 249 for self.bankdefs[i].

**Comment by hlorenzi** [comment]
I've done a complete overhaul for these systems in v0.11! This error should be no more. Could you check if it's now working as expected? Also please watch out for some of the [syntax changes in the new version](https://github.com/hlorenzi/customasm/wiki/Migrating-to-v0.11).
