### ISSUE TITLE
Weird Concatenation bug on release 0.9.1 and latest dev

### ISSUE THREAD

**Issue by ItsNineOclock** [hlorenzi/customasm#5]
Creating an instruction such as this one:
"do {value} -> 0x0 @ value[19:0]" results in a strange bug when value is 0x8000:
ff 80 00
This bug is very inconsistent. Formatting the instruction this way: "do {value} -> **0x1** @ value[19:0]" results in the bug disappearing with 0x8000, however doing this: "do 0x8000 | 0x1000" results in this output: 
1f 90 00 when it should be 10 90 00
Experiments with different operations made the bug disappear as well. Placing the "or" operation in a variable and using that results in the same bug.

I really enjoy this program, and I would really love to use it. This bug however is giving me a headache trying to try to work around it. Everywhere I turn it decides to come up again. Here's a list of things I've tried:
adjusting the #bits value in cpudef
using different numbers with value
splitting value[20:0] into value[20:16] @ value[15:0]
using different operators in the instruction definition, like | and ^

all of these resulted in the last 8 bits of the number being ff or 1f

**Comment by hlorenzi** [comment]
Aww, another one of these concatenation bugs? I'll take a look later today. Thank you for reporting it!
