### ISSUE TITLE
Feature Request: Multiline comments

### ISSUE THREAD

**Issue by clubby789** [hlorenzi/customasm#51]
Can you add support for `/* ... */` comments in asm blocks?

**Comment by p-rivero** [comment]
In my opinion, the C-style `/* */` comments would look aut of place with the assembly-style `;`. I don't know if there is a standard style for comment blocks in assembly (and I think that most assemblers don't support comment blocks, anyways).

**Comment by clubby789** [comment]
It seems to be a fairly rare feature, although most I've found that do support it seem to use that syntax.

**Comment by hlorenzi** [comment]
Maybe something like `;* comment *;` would look less out-of-place?

**Comment by p-rivero** [comment]
> Maybe something like `;* comment *;` would look less out-of-place?

Yes, I could see that being a thing. It doesn't look very standard, but more powerful syntax is always welcome.

**Comment by clubby789** [comment]
I've written a basic implementation of the `;* ... *;` idea. I've never written Rust before, so I would appreciate feedback on code quality.

**Comment by clubby789** [comment]
Closed by #57

**Comment by hlorenzi** [comment]
Oh, by the way, I think your code was fine -- you even used the same style as the rest of the file! But I was a bit afraid of indexing-out-of-bounds errors in the `src` array. I think there were also some issues that came up only after I wrote some test cases.
