### ISSUE TITLE
Donation link?

### ISSUE THREAD

**Issue by ClementNerma** [hlorenzi/customasm#54]
Hi there,

I've been using your library, CustomASM, for a while now. I'm currently making a complete [virtual machine system](https://github.com/ClementNerma/MRVM) which allows me to write more complex programs a lot faster.

I've requested [a few](https://github.com/hlorenzi/customasm/issues/21) [features](https://github.com/hlorenzi/customasm/issues/26) in the past and they have been implemented very quickly, and I see you're still very involved in the project as the recent release of the v0.11 shows, coming with a lot faster processing speed for what I've seen.

So I'd like to thank you for all your amazing work, but sadly I didn't see any donation link nor github sponsor system on your repository.

I opened this issue both because you don't have a public email adress so I couldn't contact you privately, and I think other developers who are using your library right now may be interested in donating a bit to support this library as well.

Anyway, tell me if you have a Patreon / Github Sponsor program / or anything else, and thanks again for your work on this great project ;)

**Comment by hlorenzi** [comment]
Wow, I'm so glad you've been finding it useful, and I appreciate your interest in supporting me! I'm new to this, but I've added a Patreon link to the repo's Sponsor button (I'm still not in the GitHub Sponsors program, though). Thank you again!

**Comment by ClementNerma** [comment]
Nice, I'll check this out ;)
