### ISSUE TITLE
Issue with `#labelalign`

### ISSUE THREAD

**Issue by ClementNerma** [hlorenzi/customasm#55]
Hi!

I've recently stepped against a weird bug with `#labelalign`: it seems that labels aren't aligned correctly anymore, but also that the directive isn't always recognized. Here is an example:

```
#ruledef
{
	test => 0x01 @ 0x02 @ 0x03 @ 0x04
}

a:
	test
b:
	test
```

This works fine and produce the expected result. But now if I add a  `#labelalign` directive:

```
#ruledef
{
	#labelalign 16
	test => 0x01 @ 0x02 @ 0x03 @ 0x04
}

a:
	test
b:
	test
```

This code doesn't compile anymore. I've also tried moving the directive outside the `#ruledef`, but I get the same result. Strangely, I don't have this problem with the (huge) declaration file I use in my current project with this exact same syntax, so I don't know what's causing it.

The other problem is that this directive has 0 effect on the produced code. Even with the label working, when I write `#labelalign 100000000000` it doesn't align anything :/:

I don't know where the bug comes from, but it's definitely a weird one. Do you have any idea or what's causing it?

**Comment by hlorenzi** [comment]
Sorry, I might have missed to update that directive on v0.11! I'll try to work on it shortly.

**Comment by ClementNerma** [comment]
Just to say, I just tried the latest version from the `main` branch which adds support for `#labelalign`, but the problem is still present. I don't know if this is normal or not but I thought it'd be better to indicate it in this issue :)

**Comment by hlorenzi** [comment]
Ah, yes! Did you try with `#labelalign` at the top-level, like this?

```asm
#labelalign 16
#ruledef
{
	test => 0x01 @ 0x02 @ 0x03 @ 0x04
}
```

This is the new intended way to use it.

**Comment by ClementNerma** [comment]
I just tried it and it seems the directive is correctly recognized, but I still have a bug with the program I'm assembling - it may come from my VM though so I'll dig into that.

What I also notice is that the value of the `#labelalign` directive is printed many times within the `Assembler::assemble()` method.

**Comment by hlorenzi** [comment]
OK, I fixed the debug print, and I made it only be applied to top-level labels! It's in v0.11.2 now.

**Comment by ClementNerma** [comment]
I just updated my project and it works fine now, thanks a lot ! 😃
