### ISSUE TITLE
have the #cpudef seperate from the ASM code

### ISSUE THREAD

**Issue by ProxyPlayerHD** [hlorenzi/customasm#6]
i got an idea

basically, instead of having to define the CPU for every ASM program you make why not have the entire CPU Defintion in a seperate file that just gets "called" by the program file

something like a file with a specific name, let's say "NES_CPU" which only contains the "#cpudef" part
then in the actual Assembly program instead of having to define the CPU you just use some command to call the file that has the CPU Defintion in it. something like "#cpu <file path><file name>" in this case (if the NES_CPU file is in the same directory) it would be "#cpu NES_CPU"

this way if you want to make a new program instead of having to copy the entire CPU Defintion you just use the #cpu command to call whatever CPU you want to use for the program.

of couse this means the compiler also needs to know where the CPU defintion is located but that is already defined in the #cpu command

**Comment by hlorenzi** [comment]
Do you think the `#include` directive would help in that situation? I think it might cover your needs! (In fact, the [NES example](https://github.com/hlorenzi/customasm/tree/master/examples/nes) does exactly that in `main.asm`!)

My original idea was to have some kind of global CPU repertoire, perhaps a global include directory like in C and C++ (think `#include <stdio.h>`). But that hasn't materialized yet.

Another idea was letting users have as many `#cpudef`s active as they want, and let them select which one to use with `#cpu "name_of_cpu"`. But again, I haven't yet decided on the solutions to some of the issues that can arise with this.

**Comment by ProxyPlayerHD** [comment]
i haven't noticed that in the NES example, huh interesting. you even used an extra file for specific hardware related Addresses.

features like that would be pretty amazing or does that mean they already work?

**Comment by hlorenzi** [comment]
Yes, the NES example already works!

**Comment by ProxyPlayerHD** [comment]
oh so the feature already exists but it i just didn't notice it.

was it in the documentation? if not i think it should

one more question, can you put more lines of code for an Instruction? like If, or Switch statements?
that would be really useful as the way most of my CPU designs have a lot of Instructions so that would make the work a lot easier

for example my 32b CPU uses 5 bits for a source and destination in a LD instruction. so that would be a total of 32^2 different possible LD Instructions, and i really don't want to do them by hand

**Comment by hlorenzi** [comment]
You can define an instruction multiple times, and the assembler will select the one which matches best. You could, for example, define them manually like so:

```asm
#cpudef
{
    #bits 8
    
    ; register to register
    ld ax, bx -> 0x10
    ld bx, cx -> 0x11

    ; register to memory
    ld ax, {dest} -> 0x2 @ dest[3:0]
    ld bx, {dest} -> 0x3 @ dest[3:0]
    ld cx, {dest} -> 0x4 @ dest[3:0]

    ; memory to memory
    ld {src}, {dest} -> 0x50 @ src[3:0] @ dest[3:0]
}
```

Now, if you have too many named register combinations to account for, you could use [the `#tokendef` feature](https://github.com/hlorenzi/customasm/blob/master/doc/cpudef.md#configurations) to make the implementation easier:

```asm
#cpudef
{
    #bits 8
    
    ; define the names of registers and their numerical values
    #tokendef reg
    {
        ax = 1
        bx = 2
        cx = 3
    }

    ; register to register
    ld {src: reg}, {dest: reg} -> 0x10 @ src[3:0] @ dest[3:0]

    ; register to memory
    ld {src: reg}, {dest} -> 0x20 @ src[3:0] @ dest[3:0]

    ; memory to memory
    ld {src}, {dest} -> 0x30 @ src[3:0] @ dest[3:0]
}
```

**Comment by ProxyPlayerHD** [comment]
you can assign values to strings, awesome. and when you enter a value it will then use the correct instruction and not be like "oh AX also has the same number guess they want to load from AX"

but one thing confuses me. the `ld {src: reg}, {dest: reg} -> 0x10 @ src[3:0] @ dest[3:0]`
because if you actually assemble "LD AX, BX" for example it gives you "0x10 0x12" which is 2 bytes but the instruction itself is only 1 byte long.

for better understanding here is the documentation of my 8b CPU. https://pastebin.com/g00Bsta6

here is the interesting part isolated:
```
LD Instruction: (Moves data around)
 
OPC -> SOURCE -> OPC -> DESTINATION -> OPC -> NEXT INSTRUCTION
 
0   - 1 \
1   - 0 /-----OP CODE
2   - 0 \
3   - 0 |-----SOURCE
4   - 0 /
5   - 0 \
6   - 0 |-----DESTINATION
7   - 0 /
 
 
SOURCE/DESTINATION:
 
000 - A
001 - B
010 - C
011 - H
100 - L
101 - MEM IMME              loads/stores from/to the next byte
110 - MEM ADDR IMME         loads the next 2 bytes as Address to load/store a value from/to
111 - MEM ADDR HL           uses the contents of HL as Address to load/store a value from/to
```
as you can see the Source and Destination are in the same byte as the OPCode. that is the whole point of my Instruction set. to be as compact as possible.

so i would need to somehow add the values to the Instruction

the OPcode is always 0x01 so can i just do math with the values as well?

for example with the values of the list at SOURCE/DESTINATION

```
#cpudef
{
    #bits 8
    
    ; define the names of registers and their numerical values
    #tokendef reg
    {
        AX = 0
        BX = 1
        CX = 2
        HX = 3
        LX = 4
        HL = 7
    }

    ; register to register
    ld {dest: reg}, {src: reg} -> 0x01 + (src * 4) + (dest * 32)

    ; memory to register IMME
    ld {dest}, {src: reg} -> { assert(dest <= 0xff), 0x01 + (src * 4) + (0x05 * 32)  @ dest[ 7:0] }
    ; memory to register ADDR
    ld {dest}, {src: reg} -> { assert(dest > 0xff), 0x01 + (src * 4) + (0x06 * 32)  @ dest[ 15:0] }
    
    ; register to memory IMME
    ld {dest: reg}, {src} -> { assert(src <= 0xff), 0x01 + (0x05 * 4) + (dest * 32)  @ src[ 7:0] }
    ; register to memory ADDR
    ld {dest: reg}, {src} -> { assert(src > 0xff), 0x01 + (0x06 * 4) + (dest * 32)  @ src[ 15:0] }

    ; memory to memory IMME
    ld {dest}, {src} -> ??? i would need something like a switch statement or some complex net of If statements
}
```

**Comment by hlorenzi** [comment]
You can use the slice operator `[x:y]`, the concatenation operator `@`, and binary literals to work with any number of bits. So, for example, some of your instructions could be written as:

```asm
; register to register
ld {dest: reg}, {src: reg} -> dest[2:0] @ src[2:0] @ 0b01

; memory to register ADDR
ld {dest: reg}, {src} -> dest[2:0] @ 0b110 @ 0b01 @ src[15:0]
```

Remember to always use the slice operator on the arguments of your instruction, otherwise you may get a "width not known" error.

Also, as I understand it, you are differentiating between immediate operands and memory operands by the width of the number given? So numbers `<= 0xff` are considered immediate operands, and numbers `> 0xff` are considered memory addresses? If so, it should work by using `assert`s like you did, but the compiler might not be able to disambiguate the instruction in certain cases.

Usually, there is some fixed way to differentiate between immediate operands and memory operands. For example, you might want to consider using a `#` token before an immediate value, like so:

```asm
; memory to register ADDR
ld {dest: reg}, {src} -> dest[2:0] @ 0b110 @ 0b01 @ src[15:0]

; memory to register IMM
ld {dest: reg}, #{src} -> dest[2:0] @ 0b101 @ 0b01 @ src[7:0]
```

I believe using a token like that should also help with your memory-to-memory variant:

```asm
; memory IMM to memory ADDR
ld {dest}, #{src} -> 0b110 @ 0b101 @ 0b01 @ src[7:0] @ dest[15:0]

; memory ADDR to memory ADDR
ld {dest}, {src} -> 0b110 @ 0b110 @ 0b01 @ src[15:0] @ dest[15:0]
```

**Comment by ProxyPlayerHD** [comment]
aparently you can't do stuff like this. kinda sad this would've saved me 8 lines of cpudef in this CPU

```
; ALI - REG
{ali:AL} {src:REG}			-> ali[2:0] @ src[2:0] @ 0b10

; ALI - MEM IMME
{ali:AL} #{src}				-> ali[2:0] @ 0b101 @ 0b10 @ src[7:0] @ 0x00[7:0]

; ALI - MEM ADDR
{ali:AL} {src}				-> ali[2:0] @ 0b110 @ 0b10 @ src[15:0] @ src[15:0]
```

**Comment by hlorenzi** [comment]
Ah, I see! When you tried `{ali:AL} {src:REG}`, you got an "expected identifier as first pattern token" error, right? Perhaps I can relax the requirement a bit, to allow for tokendef arguments at the start like that; it seems like a very useful feature to have.

**Comment by ProxyPlayerHD** [comment]
yes it would be useful for all instructions that have the same structure but are differently named in the Assembler.

also is there a way to have an "ELSE" to IF Statements? for example if you want an instruction to be structured differently if a specific value is present, example:

{ assert(if val > 0), 0x10 @ 0x88 else{0x88 @ 0x10}}

this would compile "0x10 0x88" if val > 0 and "0x88 0x10" if val =< 0

**Comment by hlorenzi** [comment]
Yes, you can use `assert`s for that purpose! With this, you can have different-sized outputs for each case. But if `val` cannot be determined when the instruction is encountered (for example, because it's waiting for a label that will be defined later), the assembler will always unconditionally select the last matching instruction, disregarding any `assert`s.

You can also use the ternary conditional operator `? :` inside a single output expression, but then you must have same-sized outputs for every case, like so:

```asm
ld {val} -> val > 0 ? { 0x10 @ 0x88 } : { 0x88 @ 0x10 }
```

But note that the code above won't work right now. You could fix it by just slicing it off at the end:

```asm
ld {val} -> (val > 0 ? { 0x10 @ 0x88 } : { 0x88 @ 0x10 })[15:0]
```

(And you can also use line breaks to make everything easier to read.)
