### ISSUE TITLE
Strings as paramaters

### ISSUE THREAD

**Issue by clubby789** [hlorenzi/customasm#60]
I wasn't able to find an example of how one might go about doing something like this:
```asm
#ruledef
{
    pushn {n: u8}, {data: str}
}

pushn 4, "test"
```
I saw mention of the `#d` directive in the migration guide, but not of how it would be used in context.

**Comment by p-rivero** [comment]
Just remove the `: str` part. Like this:
```
#ruledef
{
    pushn {n: u8}, {data} => 0xAB @ n @ data
}

pushn 4, "test"     ; Becomes ab 04 74 65 73 74
pushn 5, "01234"    ; Becomes ab 05 30 31 32 33 34
```

**Comment by clubby789** [comment]
Ah, thanks! Is there a way to add an (optional) terminating null byte? `"test\0"` or `"test" \x00` for example.

**Comment by p-rivero** [comment]
Yes, `"test\0"` should work.

**Comment by clubby789** [comment]
Thanks.
