### ISSUE TITLE
Assembler terminates without error message

### ISSUE THREAD

**Issue by p-rivero** [hlorenzi/customasm#64]
I found a small bug on the latest version 0.11.3. Let's say I want to assemble the following code:
```asm
#subruledef REG {
    my_reg => 0xA
}
#ruledef {
    test {Addr: u16} => 0x1 @ Addr
    test {register: REG} + {Not_Imm: u16} => register`4 @ Imm
}

test my_reg + 1
```
Version 0.11.2 succesfully identifies that I was trying to use the second instruction (`test {register: REG} + {Not_Imm: u16}`), and that I had made a typo (I typed `Not_Imm: u16` instead of `Imm: u16`). Therefore, it correcly displays the error message
```
error: unknown variable
test {register: REG} + {Not_Imm: u16} => register`4 @ Imm
                                                      ^^^
```
However, version 0.11.3 doesn't show *any* error message and just terminates with exit code 1. Its only output is
```
customasm v0.11.3 (2020-12-05, x86_64-pc-windows-gnu)
assembling `test.asm`...
```

Again, it's a pretty small bug that only happens on this edge case, but it's rather confusing to not have *any* indication on what went wrong, specially when assembling large files.

**Comment by clubby789** [comment]
Tracked the problem down to https://github.com/hlorenzi/customasm/blob/030ed1031e5da8778464f299105573c2a32497ca/src/diagn/report.rs#L242-L249. The for loop isn't run at all.
