### ISSUE TITLE
Feature request: Option for calling cpp before assembling

### ISSUE THREAD

**Issue by p-rivero** [hlorenzi/customasm#68]
I think it would be great to have an option to tell customasm that it should call `cpp` on the input files before attempting to assemble them, [as described on this comment](https://github.com/hlorenzi/customasm/issues/52#issuecomment-730032515).
I'm currently using a makefile:
```make
output = out.hex
temporary = temp.preprocessed
target = ROM.asm

rom: customasm.exe
	cpp -x assembler-with-cpp -nostdinc -CC -undef -P $(target) > $(temporary)
	./customasm.exe $(temporary) -o $(output)
	rm -f $(temporary)
```
But it would be great if customasm supported it natively, so that you could call customasm directly. Something like:
```sh
./customasm.exe -cpp -o out.hex ROM.asm
```

**Comment by hlorenzi** [comment]
I'm more inclined to support the needed directives natively instead. If I remember correctly, you're using #define for substitutions and #ifndef for include guards?

I was thinking about adding some `#fn` directive to define functions, which seem to be enough for your use case -- we wouldn't need preprocessor substitutions, right?

Additionally, I think I'd add something like a `#once` directive to skip a file being included more than once.

**Comment by p-rivero** [comment]
Yes, I'm mainly using macros and include guards, so having those on customasm would be great.
I think I'm using substitutions, actually. I recently added `#define sizeof(Begin)  (pc - Begin)*2` so that I can get the size in bytes of a data region as a constant and it has become an extremely useful feature:
```asm
args:
#d16    1, 2, 3, 4, 5
.size = sizeof(args)

mov t0, args.size
```

Are there any ways to do something like that? And how would `#fn` work, exactly?

**Comment by hlorenzi** [comment]
I think having a `.size` or `.len` automatically calculated for you is very useful, indeed! I'll see what I can do.
I'll close this and create a new issue specifically for that suggestion.
