### ISSUE TITLE
Contributing wiki documentation

### ISSUE THREAD

**Issue by rj45** [hlorenzi/customasm#71]
I spent some time today adding a few pages to the wiki documentation.

I mostly just adapted the old documentation in the docs folder, and I tried to double check against the source code to make sure it was accurate but I may have made some mistakes. I may also have missed some information, and/or misinterpreted what you had it mind for some pages. But well, it's a start at least :-)

Anyway, I give any copyright to you and I do not need any credit. Feel free to modify/edit them in any way, I will not be offended.

[customasm.wiki.zip](https://github.com/hlorenzi/customasm/files/6055822/customasm.wiki.zip)

**Comment by p-rivero** [comment]
This looks really good! I hope it gets added to the wiki soon.

**Comment by hlorenzi** [comment]
That's amazing help! Thank you so much! I've added the pages to the Wiki, with slight modifications.
