### ISSUE TITLE
"error: multiple matches for instruction" despite instruction mnemonic being different

### ISSUE THREAD

**Issue by ProxyPlayerHD** [hlorenzi/customasm#72]
I'm back, and I broke the assembler again.
while updating my existing CPU definition files for the newest version i raw into a weird issue.
basically the assembler would fail to assemble a instruction because it was aparently the same as another instruction.
after commenting out all instructions and individually uncommenting them i found which one.

long story short: [IMAGE](https://i.imgur.com/o25XzQi.png) (I'm sorry but the opportunity was perfect)

i made a small test CPU file to see if it could be replicated easily, and it can!
```
#bits 8

#subruledef REG
{
	R0 => 0b00
	R1 => 0b01
	R2 => 0b10
	R3 => 0b11
}

#ruledef
{
	
	LD {RD:REG}, ({ADDR})	=> RD @ 0b000000 @ ADDR`16
	LD {RD:REG}, {VALUE}	=> RD @ 0b111111 @ VALUE`8
	
}

; LD R0, (0x1234)	this will fail to assemble

; LD R0, 0x00		this assembles just fine
```
obviously the instruction to test has to be uncommented first.
it appears that the assembler is ignoring round brackets (same test with sqaure brackets makes it assemble normally)
is this a result of the changes done in 0.11.4 to allow the masking subruledefs, or is it completely unrelated?

**Comment by p-rivero** [comment]
I think this issue has existed for a long time. Customasm thinks the parenthesis are part of an expression that needs to be evaluated as an integer (something like `LD R0 (6+8)*4`), so technically both rules are identical.
I originally wanted to use `( )` for my assembly language, but I switched to `[ ]` for this reason.

**Comment by hlorenzi** [comment]
Hmm, using parentheses like this was supposed to work... Since it's giving me a "multiple matches" error, maybe I can fix it by having it select the pattern with the "most specificity"? I'm thinking "specificity" would be probably be realized as the number of fixed tokens in the pattern, so having the parentheses there would increase the specificity, and it would win over the alternative without parentheses.

**Comment by ProxyPlayerHD** [comment]
p-rivero, i've used parentheses in mnemonics for years and it has always worked perfectly fine, only after 0.11.4 did it suddendly break. so i doubt this is an existing issue.

**Comment by p-rivero** [comment]
@ProxyPlayerHD you are right, version 0.11.2 works just fine. Apparently the issue was introduced with version 0.11.3, and it's still present in 0.11.4

**Comment by hlorenzi** [comment]
I ended up going the "specificity" route, which seems to work wonders. The code I had to rewrite for this should also help with issue #69!
