### ISSUE TITLE
The bit slice output of a long decimal negative number seems wrong.

### ISSUE THREAD

**Issue by gpthimble** [hlorenzi/customasm#77]
The bit slice output of a long decimal negative number seems wrong.

Define the rule like this:
```
#ruledef{
test {value:s32} => value[31:16]
}

```
Try to assemble this instruction:
`test -349678887`

The output is :
```
 outp | addr | data

  0:0 |    0 | eb 29 ; test -349678887
```

But
-349678887 in Hex is EB2852D9

The correct output should be
```
 outp | addr | data

  0:0 |    0 | eb 28 ; test -349678887
```

Any idea?

**Comment by hlorenzi** [comment]
Oh, that's a nasty, nasty bug! Thank you so much for reporting it. I've managed to fix it, and I'll release a new version soon!

**Comment by gpthimble** [comment]
Thank you very much for the quick update, now the customASM is perfectly working for my processor [SystemOT](https://github.com/gpthimble/Home-Brew-Computer). 
If your're interesting, SystemOT is a 32-bit soc softcore, I have ported the LCC 3.6 c compiler, and use customASM as the assembler, now the whole system is working, and I also ported the Dhrystone2.1 benchmark program.
