### ISSUE TITLE
[0.11.7] "Index out of bounds: the len is 0 but the index is 0" when assembling

### ISSUE THREAD

**Issue by ProxyPlayerHD** [hlorenzi/customasm#81]
here the entire error:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/syntax/parser.rs:406:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

and here the file i tried to assemble: [PASTEBIN](https://pastebin.com/ukjjSJ0R) and the CPU File: [PASTEBIN](https://pastebin.com/pLYVy6ZL)

i know that it worked before so this is a bit confusing. on a different note, where are the changelogs for each version being released? it's not in the release tab.

**Comment by ProxyPlayerHD** [comment]
yes there was a typo.
you can test if this one works: https://pastebin.com/4gfhCaNt

**Comment by hlorenzi** [comment]
You should not see the crash anymore in v0.11.8!

**Comment by ProxyPlayerHD** [comment]
``yep it seems to work, but it still cannot assemble something due to either multiple matches or because of no match.
i thought if there were multiple matches it would just pick the first in the list? for example:
```
;	Branch D8/16
	BRA {DEST}	=> {rel = (DEST - (pc + 2)), assert(rel <= 127 && rel >= -128 && rel != 0), 0b0110 @ 0b0000 @ rel`8}
	BRA {DEST}	=> {rel = (DEST - (pc + 2)), assert(rel <= 32767 && rel >= -32768), 0b0110 @ 0b0000 @ 0x00 @ rel`16}
```
basically this is the difference between a branch that uses an 8 bit signed offset, and a 16 bit signed offset.
if an offset fits into the first instruction it will also fit into the second one, so should i make the assert of the second one exclude values between 127 and -128 to make sure only 1 matches?
sometimes i wish there was a commandline parameter that would, in case of multiple matches, just pick the one that assembles into fewer bits/bytes.

other instructions are not assembing either because their assert is checking variables that are inside subruledef's.
for example:
```
ADD.B {DSRC:AM_BL7I8}		=> {assert(SRC == 0 || SRC > 8), 0b00000110 @ 0b00 @ DSRC}
```
```
#subruledef AM_BL7I8
{
	{REG:Dn}, #{SRC:i8}				=> 0b000 @ REG`3 @ 0x00 @ SRC`8					; Dn
	; An
	({REG:An}), #{SRC:i8}				=> 0b010 @ REG`3 @ 0x00 @ SRC`8					; (An)
	({REG:An})+, #{SRC:i8}				=> 0b011 @ REG`3 @ 0x00 @ SRC`8					; (An)+
	-({REG:An}), #{SRC:i8}				=> 0b100 @ REG`3 @ 0x00 @ SRC`8					; -(An)
	({OFF:s16}, {REG:An}), #{SRC:i8}		=> 0b101 @ REG`3 @ 0x00 @ SRC`8 @ OFF`16			; (D16, An)
	({OFF:s8}, {REG:An}, {EXT0:Xn}), #{SRC:i8}	=> 0b110 @ REG`3 @ 0x00 @ SRC`8 @ EXT0`4 @ 0b0000 @ OFF`8	; (D8, An, Xn)
	{DATA}.W, #{SRC:i8}				=> 0b111000 @ 0x00 @ SRC`8 @ DATA`16				; (D16)
	{DATA:s16}, #{SRC:i8}				=> 0b111000 @ 0x00 @ SRC`8 @ DATA`16				; (D16)
	{DATA}.L, #{SRC:i8}				=> 0b111001 @ 0x00 @ SRC`8 @ DATA`32				; (D32)
	{DATA:i32}, #{SRC:i8}				=> 0b111001 @ 0x00 @ SRC`8 @ DATA`32				; (D32)
	; (D16, PC)
	; (D8, PC, Xn)
}
```

**Comment by hlorenzi** [comment]
It does not take declaration order into consideration anymore! In that case, you must use extra asserts to make sure your arguments match exclusively one rule or the other. Your suggestion for an automatic choice of the rule that assembles into the least amount of bits is very interesting! I think that would make for a nice feature to have.

The other issue is more complicated, though. Is it possible to put the assert in the subrule instead? Or maybe you could test only part of the subrule's return value on your main rule? (But I can see the SRC part isn't always in the same position...)

**Comment by ProxyPlayerHD** [comment]
i don't think i could put the assert in the subruledef itself as multiple different instructions are using that same exact subruledef.

to be more specific about why the assert exists, the 68k has an ADD Quick Instruction, which is functionally the same as ADD Immediate, but it only allows values between 1 and 8 to be used, but therefore it requires 2 bytes less than Add Immediate.
since both instructions can share the same mnemonic i need the assembler to check which one of these to use.

before i had an Assert statement on the ADDQ Instruction:
```
ADD.B {DEST:AM_BL9}, #{SRC}	=> {assert(SRC >= 1 && SRC <= 8), 0b0101 @ SRC @ 0b0 @ 0b00 @ DEST}
```
to make sure it only matches when the value is between 1 to 8.
and the reverse Assert for the regular ADD Instruction too:
```
ADD.B {DEST:Dn}, #{SRC:i8}	=> {assert(SRC == 0 || SRC > 8), 0b1101 @ DEST @ 0b000 @ 0b111 @ 0b100 @ 0x00 @ SRC`8}
```
to make sure it only works wih values equal to or larger than 8.
and it works, but then i tried to do the same with ADDI so that it would also unmatch the instruction if SRC is between 1 and 8, but as you can see that doesn't work so well.

it would be pretty awesome if you could assign a sort of "stalemate solver" to each ruledef (including subruledefs), basically telling it what to do if it has multiple matching instructions. i can think of 5 potentially useful solvers from the top of my head:
* Random, just choose one of the matching Instructions
* Order, choose the first Instruction that matches, ignoring any that may also match further down
* Reverse Order, same as order but choose the last matching Instruction encountered
* Size, choose the smallest matching Instruction
* Reverse Size, choose the largest matching Instruction

**Comment by hlorenzi** [comment]
I do really like the idea of selecting the smallest instruction in the case of a multiple match. I've been writing a program for the 6502, and it would really simplify the [CPU definition](https://github.com/hlorenzi/customasm/blob/main/examples/nes/cpu6502.asm) if that feature existed.

**Comment by ProxyPlayerHD** [comment]
optimizing the Zero page for the 65(c)02 is pretty straight forward. you just check if the High byte of the address is equal to 0, if yes use the Zero page Addressing mode, if not use the Absolute Addressing mode. i did that for my 65C02 CPU File, and it works great.
sadly the same doesn't work for CPUs like the 65CE02 or 65816 as the Zero page (Direct Page) can be moved around. so with a Stateless Assembler like CustomASM it would not be possible to optimize such instructions automatically.

the idea of #76 would solve stuff like this perfectly, but is it too complex to implement?

**Comment by hlorenzi** [comment]
Sorry if I let the conversation die 😅 I want to put as much thought as possible into every response, but sometimes I don't have the time due to my job. But rest assured I do read every message! I'll try to get back to that issue when I'm able to put a little more thought into it.

I've implemented the automatic selection of the smallest instruction on v0.11.9. It's the default now, because I feel like that's what you want most of the time, and it's working nicely for the 6502. But you can always override the behavior with asserts. Let me know if there are any problems with this.
