### ISSUE TITLE
[0.11.8] "expected identifier" after #bankdef

### ISSUE THREAD

**Issue by ProxyPlayerHD** [hlorenzi/customasm#82]
All i'm trying to do is use this:
```
#bankdef "whatever"
{
  #addr 0xFC00
  #size 0x0400
  #outp 0
}
```
and it's formatted exactly like the wiki says, so either the wiki is outdated or i'm overlooking something

**Comment by hlorenzi** [comment]
Oops! The wiki was outdated. You must name the bank without using quotation marks! I've fixed it in the wiki now.

**Comment by ProxyPlayerHD** [comment]
oh i see, it's working now. thanks!
