### ISSUE TITLE
[0.11.9] First instruction in CPU file can never be matched

### ISSUE THREAD

**Issue by ProxyPlayerHD** [hlorenzi/customasm#89]
weird issue, whatever instruction you first defined in the CPU file/ruledef can never be used in a program as it will just throw a "no match for instruction found" error.

i noticed this when i assmbled a program for the 65C02 and any `ADC #` instruction threw that error, that instruction is the first one in that CPU File so to test my theory i just added a useless dummy instruction before it, and suddendly the program assembled perfectly fine.

still to provide actual code to replicate this, i made this simple example:

```
#ruledef
{
	#bits 8
	
	;ZEROTH	=> 0x00	;uncomment this instruction for it to assemble (unless you actually use ZEROTH in the program)
	FIRST	=> 0x01
	SECOND	=> 0x02
	THIRD	=> 0x03
}

THIRD
FIRST	;or comment this instruction for it to assemble
SECOND
```

**Comment by hlorenzi** [comment]
Ah! The `#bits` directive should go outside the `ruledef` block on v0.11 upwards. The assembler is interpreting the directive as part of the first instruction's pattern, so that's why you don't get a match.

**Comment by ProxyPlayerHD** [comment]
welp, i somehow missed that, probably because the CPU file i was using was still pretty old and i never really updated it.
thanks man!
