### ISSUE TITLE
Bracket after newline

### ISSUE THREAD

**Issue by hlorenzi** [hlorenzi/customasm#91]
### Discussed in https://github.com/hlorenzi/customasm/discussions/90

<div type='discussions-op-text'>

<sup>Originally posted by **MSlockbo** June 23, 2021</sup>
Not sure if this is a bug or not, I followed the wiki, but I clearly messed something up:
![image](https://user-images.githubusercontent.com/86361573/123150517-74eadd80-d430-11eb-96cd-cb84e81f660c.png)

Edit:
It works if I put a character in front of the open bracket.

Also, apologies for putting this in the wrong spot, I forgot GitHub has an issues tab now and couldn't figure out how to migrate this post.</div>

**Comment by hlorenzi** [comment]
The assembler is probably expecting you to use a bracket-style slice (as in `reg[7:0]`) but it shouldn't be allowed with a newline in between... I'll work on a fix!

**Comment by MSlockbo** [comment]
Cool, thank you!
