### ISSUE TITLE
Instructions can't emit 0 bits

### ISSUE THREAD

**Issue by b0iizz** [hlorenzi/customasm#96]
Hi, I'm creating my own 8-bit instruction set at the moment and have been using customasm and it works great for the most part. But then I ran into the following issue:
```
cpy.8 {dst: REG8}, {src: REG8} => {	;emit nothing when copying to itself
	assert(dst == src)
}
cpy.8 {dst: REG8}, {src: REG8} => {
	assert(dst != src)
	0b10 @ dst @ src 
}
```
From my understanding, when i call f. e. `cpy.8 a, a` it should reject the 2nd variant and match the 1st, but instead an assertion error got thrown. Am I understanding something wrong. If I do, then this would be a nice feature.

**Comment by b0iizz** [comment]
I actually realized that the issue is that the instruction doesn't match because it does not emit any bits. But then the issue becomes, why can't it?

**Comment by hlorenzi** [comment]
To emit nothing, use something like the following:
```asm
cpy.8 {dst: REG8}, {src: REG8} => {
    assert(dst == src)
    0`0
}
```
(Your original code was returning the value of the `assert`, which is void, so the assembler was disregarding that particular rule, trying to resolve the next one.)

I haven't really tested instructions which emit nothing, so let me know if something else comes up!

**Comment by b0iizz** [comment]
Thanks a lot! I will be sure to contact you if something weird comes around!
